{**********************************************************************
    This file is part of ax_pokl run time library
    Copyright (c) 2014 by ax_pokl

    This file is part of Unit Display

    See the file COPYING.FPC, included in this distribution,
    for details about the copyright.
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

    这个文件是ax_pokl运行时库的一部分
    版权所有（c）2014年ax_pokl

    这个文件是Display单元库的一部分

    版权信息请参考COPYING.FPC。
 **********************************************************************}

{ Mouse Key codes }
      M_LEFT=0;
      M_RIGHT=1;
      M_MIDDLE=2;
{ Keyboard Key codes }
      K_LBUTTON=1;
      K_RBUTTON=2;
      K_CANCEL=3;
      K_MBUTTON=4;
      K_BACK=8;
      K_TAB=9;
      K_CLEAR=12;
      K_RETURN=13;
      K_SHIFT=16;
      K_CONTROL=17;
      K_MENU=18;
      K_PAUSE=19;
      K_CAPITAL=20;
      K_ESCAPE=27;
      K_SPACE=32;
      K_PRIOR=33;
      K_NEXT=34;
      K_END=35;
      K_HOME=36;
      K_LEFT=37;
      K_UP=38;
      K_RIGHT=39;
      K_DOWN=40;
      K_SELECT=41;
      K_PRINT=42;
      K_EXECUTE=43;
      K_SNAPSHOT=44;
      K_INSERT=45;
      K_DELETE=46;
      K_HELP=47;
      K_0=48;
      K_1=49;
      K_2=50;
      K_3=51;
      K_4=52;
      K_5=53;
      K_6=54;
      K_7=55;
      K_8=56;
      K_9=57;
      K_A=65;
      K_B=66;
      K_C=67;
      K_D=68;
      K_E=69;
      K_F=70;
      K_G=71;
      K_H=72;
      K_I=73;
      K_J=74;
      K_K=75;
      K_L=76;
      K_M=77;
      K_N=78;
      K_O=79;
      K_P=80;
      K_Q=81;
      K_R=82;
      K_S=83;
      K_T=84;
      K_U=85;
      K_V=86;
      K_W=87;
      K_X=88;
      K_Y=89;
      K_Z=90;
      K_LWIN=91;
      K_RWIN=92;
      K_APPS=93;
      K_NUMPAD0=96;
      K_NUMPAD1=97;
      K_NUMPAD2=98;
      K_NUMPAD3=99;
      K_NUMPAD4=100;
      K_NUMPAD5=101;
      K_NUMPAD6=102;
      K_NUMPAD7=103;
      K_NUMPAD8=104;
      K_NUMPAD9=105;
      K_MULTIPLY=106;
      K_ADD=107;
      K_SEPARATOR=108;
      K_SUBTRACT=109;
      K_DECIMAL=110;
      K_DIVIDE=111;
      K_F1=112;
      K_F2=113;
      K_F3=114;
      K_F4=115;
      K_F5=116;
      K_F6=117;
      K_F7=118;
      K_F8=119;
      K_F9=120;
      K_F10=121;
      K_F11=122;
      K_F12=123;
      K_F13=124;
      K_F14=125;
      K_F15=126;
      K_F16=127;
      K_F17=128;
      K_F18=129;
      K_F19=130;
      K_F20=131;
      K_F21=132;
      K_F22=133;
      K_F23=134;
      K_F24=135;
      K_NUMLOCK=144;
      K_SCROLL=145;
      K_LSHIFT=160;
      K_LCONTROL=162;
      K_LMENU=164;
      K_RSHIFT=161;
      K_RCONTROL=163;
      K_RMENU=165;
